### ISSUE TITLE
Build instructions for ARM

### ISSUE THREAD

**Issue by mrbluecoat** [boratanrikulu/durdur#9]
In case it helps others, here were additional steps I needed to perform to build on ARM:

```
sudo apt install -y clang llvm libbpf-dev

sudo ln -s /usr/include/aarch64-linux-gnu/asm /usr/include/asm
sudo ln -s /usr/include/aarch64-linux-gnu/bits /usr/include/bits
sudo ln -s /usr/include/aarch64-linux-gnu/sys /usr/include/sys
sudo ln -s /usr/include/aarch64-linux-gnu/gnu /usr/include/gnu

env GOOS=linux GOARCH=arm64 CGO_ENABLED=0 make build

sudo cp build/durdur /usr/local/bin/
```

**Comment by boratanrikulu** [comment]
Nice, thank you!

Durdur is still considered as not ready for production usages. That's why it's not versioned yet and not have any pre-built binaries.  
But I will re-active this project and I plan to make a versioned release.
